# Generated by Django 4.2.1 on 2023-05-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=10, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha_nacimiento', models.DateField()),
                ('telefono1', models.IntegerField()),
                ('telefono2', models.CharField(max_length=15, verbose_name='+56955109007')),
                ('cuidad', models.CharField(max_length=50, verbose_name='Cuidad')),
                ('vivienda', models.IntegerField(choices=[(1, 'Casa con patio grande'), (2, 'Casa con patio pequeño'), (3, 'Casa sin patio'), (4, 'Departamento')])),
            ],
        ),
    ]
